#FROM sensoriant.azurecr.io/priv-comp/crosscompilers-alpine:attestation
#FROM  sconecuratedimages/sensoriant:pytorch-1.5.1-ubuntu18.04-scone5.0.0-v0.1
FROM sensoriant.azurecr.io/priv-comp/python-3.8.1-ubuntu:11022020

RUN apt-get update

